### ISSUE TITLE
Create Gameplay

### ISSUE THREAD

**Issue by IdrissDimson** [Devaprise/Targo-Tap-2#1]
- [x] Buttons
- [x] Scoring
- [x] Timer
- [x] Number shuffling

**Comment by Grandzam** [comment]
This has many sub-tasks involved. Here are some: Buttons, score, timer and number shuffling

**Comment by IdrissDimson** [comment]
i'll add that to a todo list on here

**Comment by IdrissDimson** [comment]
gameplay 3/4 done but there are bugs. the specific bugs will be on seperate issues.

**Comment by IdrissDimson** [comment]
done!
